version: '3.7'

services:
  intra-mariadb:
    image: mariadb:10.5.21
    container_name: intra-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: awef4865
      MYSQL_DATABASE: event_management_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "33061:3306"
    volumes:
      - ./intra-mariadb-data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  intra-adminer:
    image: adminer
    container_name: intra-adminer
    ports:
      - "8080:8080"

volumes:
  intra-mariadb-data: