homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
